apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopussamples-octopub-audit-development
  annotations:
    codefresh.io/product: octopussamples-octopub-audit
spec:
  project: default
  destination:
    namespace: cf-development
    server: https://kubernetes.default.svc
  source:
    path: codefresh/helm/octopub-audits/development
    repoURL: https://github.com/OctopusSolutionsEngineering/octopub.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=false
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
